# Generated by Django 3.1 on 2020-08-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_post_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='article_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
